kind: Secret
apiVersion: v1
metadata:
  name: production-{{ .Values.apiCast.name }}-portal-admin-credentials
  namespace: '{{ .Values.apiCast.namespace }}'
data:
  AdminPortalURL: {{ printf "https://%s@%s" .Values.apiManager.portalAdminToken .Values.apiManager.portaAdminHost | b64enc }}
